### PR TITLE
Convert all epochs of a session

### PR DESCRIPTION
**Pull request by alessandratrapani**
This PR is for the convert session script.
Each session has 6 epochs: "2ret", "3ori", "4ori", "5stim", "6stim" and "7expt", that will be stored individually in a nwb file. 
Each nwb file :
- will report the same session_id
- will be saved as {session_id}_{epoch_name}.nwb
- will be saved in outpur_dir_path / {session_id} folder

### CODE REVIEW

**Comment by alessandratrapani** [comment]
[Here](https://catalystneuro-processing.s3.us-east-2.amazonaws.com/adesnik-lab-to-nwb/2023119_w57_1/) a stub version for all converted epochs

**Comment by weiglszonja** [comment]
> [Here](https://catalystneuro-processing.s3.us-east-2.amazonaws.com/adesnik-lab-to-nwb/2023119_w57_1/) a stub version for all converted epochs

Thanks, I only have a few comments/questions:
- `location` should follow the naming convention of the Allen Mouse Brain Atlas, so "V1" would be "VISp" (but should double-check) --> this should be changed in `ImagingPlane`s (and `PatternedOptogeneticStimulusSite` too probably), what you currently have for location is "Primary visual cortex (V1), 200 um below pia" can go to the "description" field of the ImagingPlane, which currently has a default value so this is going to be more informative. 
- Do you need to do any time alignment or is it aligned already?
- In [2023119_w57_1_3ori.nwb](https://s3.console.aws.amazon.com/s3/object/catalystneuro-processing?region=us-east-2&bucketType=general&prefix=adesnik-lab-to-nwb/2023119_w57_1/2023119_w57_1_3ori.nwb) you have a typo in `TimeIntervals` `description` field "Simple Visual Stimuls"

I would also discuss two issues that `nwbinspector` found for [2023119_w57_1_5stim.nwb](https://s3.console.aws.amazon.com/s3/object/catalystneuro-processing?region=us-east-2&bucketType=general&prefix=adesnik-lab-to-nwb/2023119_w57_1/2023119_w57_1_5stim.nwb):
Screenshot 2024-02-05 at 14 56 24

The first looks weird, have you seen it before?
The second is about the ascending order of time columns, looking at the `start_time` column they are indeed not in ascending order:
Screenshot 2024-02-05 at 15 03 48
Can you fix that?

I'm also wondering whether it would be worth adding a `session_description` that would provide a distinction between the files, because for now they all have the same "Headfixed 2-photon calcium imaging and photostimulation of visual cortex."
like for "2ret" files you could add "with retinotopy" etc. What do you think?

**Comment by alessandratrapani** [comment]
> * `location` should follow the naming convention of the Allen Mouse Brain Atlas, so "V1" would be "VISp" (but should double-check) --> this should be changed in `ImagingPlane`s (and `PatternedOptogeneticStimulusSite` too probably), what you currently have for location is "Primary visual cortex (V1), 200 um below pia" can go to the "description" field of the ImagingPlane, which currently has a default value so this is going to be more informative.

Thanks! I changed that and add it to description (both for ImagingPlane and PatternedOptogeneticStimulusSite)

> * Do you need to do any time alignment or is it aligned already?

No, both visual stimuli and holo stimuli uses ScanImage timestamps already. Everything is aligned to ScanImage first .tiff

> * In [2023119_w57_1_3ori.nwb](https://s3.console.aws.amazon.com/s3/object/catalystneuro-processing?region=us-east-2&bucketType=general&prefix=adesnik-lab-to-nwb/2023119_w57_1/2023119_w57_1_3ori.nwb) you have a typo in `TimeIntervals` `description` field "Simple Visual Stimuls"
 
Good catch thanks!

**Comment by alessandratrapani** [comment]
> I would also discuss two issues that `nwbinspector` found for [2023119_w57_1_5stim.nwb](https://s3.console.aws.amazon.com/s3/object/catalystneuro-processing?region=us-east-2&bucketType=general&prefix=adesnik-lab-to-nwb/2023119_w57_1/2023119_w57_1_5stim.nwb):

Yes, I noticed these too.
For what concern the OptogeneticStimulusSite, I am not quite sure what causes this, I am going to investigate



> The second is about the ascending order of time columns, looking at the `start_time` column they are indeed not in ascending order:
> Can you fix that?

Yes I am working on this right now

**Comment by alessandratrapani** [comment]
> I'm also wondering whether it would be worth adding a `session_description` that would provide a distinction between the files, because for now they all have the same "Headfixed 2-photon calcium imaging and photostimulation of visual cortex."
> like for "2ret" files you could add "with retinotopy" etc. What do you think?

Yes, good idea! I will ask them to give me more info on each epoch. For now, I will add a simple description to disambiguate each nwb file description.

**Comment by alessandratrapani** [comment]
@weiglszonja only thing left is to fix the OptogeneticStimulusSite best practice violation. I can't understand where the problem is.

**Comment by weiglszonja** [comment]
Can you open an issue for this? Maybe it would be good to open at the extension repo and tag Ryan also?

then we can propagate it to either nwbinspector or pynwb depending whether this is  a pynwb validation issue or a check function in nwbinspector that is triggered.

**Review by weiglszonja — APPROVED** [review]
Besides the last comment, the latest changes LGTM.

**Pull request merged**
