### PR TITLE
Imaging data conversion

### PR DESCRIPTION
**Pull request by alessandratrapani**
This PR is for adding the imaging extractor (edit: Now it is including also the imaging interface #5  and the segmentation interface #6 )
I am working with a ScanImage dataset where a single session recording is chunked over time in multiple .tif files.
Currently, the ScanImage extractor extracts the entire video from one .tif file.
I need to pass a folder_path where all the .tif files of one session are stored-

- [x] add multi plane imaging extractor
- [x] add single plane imaging extractor
- [ ] separate segmentation data into epochs (same as raw imaging)

### CODE REVIEW

**Review by pauladkisson — CHANGES_REQUESTED** [review]
1. Instead of inheriting from ImagingExtractor, you should inherit from MultiImagingExtractor.  That way you can avoid redefining all of the functions, and in your __init__ you can just do the file path logic and then call super().__init__()
2. I think we should add this multi file logic into roiextractors. Originally I had thought it would be a trivial addition to the library, so I didn't include it. But, this experience has shown that even if it's only a few lines of code, it can be worthwhile to have a dedicated class. In the generic MultiFileMultiPlaneScanImageTiffImagingExtractor, though, we will want to pass in a list of file names rather than a folder path to avoid file naming ambiguities.
3. It would be nice to see an example script running this code on the actual data.

**Comment by alessandratrapani** [comment]
Thanks for the review @pauladkisson.
I addressed point 1 and point 3 of your review. 
For the second point, should I open a PR on roiextractor?

**Comment by pauladkisson** [comment]
> For the second point, should I open a PR on roiextractor?

yes, pls! if you have a bit of time.

**Review by pauladkisson — APPROVED** [review]
LGTM

**Pull request merged**
